name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
      branches:
          - main
      # Review gh actions docs if you want to further define triggers, paths, etc
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
      name: Deploy to GitHub Pages
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
            with:
                fetch-depth: 0

          - uses: pnpm/action-setup@v3
            with:
                version: 8

          - uses: actions/setup-node@v4
            with:
                node-version: 20
                cache: pnpm

          - uses: bitovi/github-actions-react-to-github-pages@v1.2.4
            with:
              install_command: 'pnpm install'
              build_command: 'pnpm build'
              path: build
